-- MySQL Script generated by MySQL Workbench
-- Thu Oct 27 00:12:26 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema krabby_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema krabby_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `krabby_db` DEFAULT CHARACTER SET utf8mb4 ;
USE `krabby_db` ;

-- -----------------------------------------------------
-- Table `krabby_db`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `krabby_db`.`category` (
  `id_category` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(150) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_category`))
ENGINE = InnoDB
AUTO_INCREMENT = 18
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `krabby_db`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `krabby_db`.`product` (
  `id_product` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(150) NOT NULL,
  `caracteristicas` VARCHAR(150) NOT NULL,
  `precio` DECIMAL(10,2) NOT NULL,
  `imagen` VARCHAR(150) NOT NULL,
  `id_category` INT(11) NOT NULL,
  PRIMARY KEY (`id_product`),
  INDEX `id_category_idx` (`id_category` ASC) VISIBLE,
  CONSTRAINT `id_category`
    FOREIGN KEY (`id_category`)
    REFERENCES `krabby_db`.`category` (`id_category`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 36
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `krabby_db`.`roll_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `krabby_db`.`roll_user` (
  `id_roll` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_roll`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `krabby_db`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `krabby_db`.`users` (
  `id_user` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(150) NOT NULL,
  `apellido` VARCHAR(150) NOT NULL,
  `telefono` INT(11) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `password` VARCHAR(50) NOT NULL,
  `imagen` VARCHAR(150) NOT NULL,
  `roll_id` INT(11) NOT NULL,
  PRIMARY KEY (`id_user`),
  INDEX `id_roll_idx` (`roll_id` ASC) VISIBLE,
  CONSTRAINT `id_roll`
    FOREIGN KEY (`roll_id`)
    REFERENCES `krabby_db`.`roll_user` (`id_roll`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `krabby_db`.`user_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `krabby_db`.`user_product` (
  `id_user_product` INT(11) NOT NULL AUTO_INCREMENT,
  `id_user` INT(11) NOT NULL,
  `id_product` INT(11) NOT NULL,
  PRIMARY KEY (`id_user_product`),
  INDEX `id_product_idx` (`id_product` ASC) VISIBLE,
  INDEX `id_user_idx` (`id_user` ASC) VISIBLE,
  CONSTRAINT `id_product`
    FOREIGN KEY (`id_product`)
    REFERENCES `krabby_db`.`product` (`id_product`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `krabby_db`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
